
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Web.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PasswordReminder
{

    public int Id { get; set; }

    public string hash_string { get; set; }

    public string creation_date { get; set; }

    public int UzytkownikId { get; set; }



    public virtual Uzytkownik Uzytkownik { get; set; }

}

}
