//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Przepis
    {
        public int Id { get; set; }
        public string nazwa { get; set; }
        public string opis { get; set; }
        public string przygotowanie { get; set; }
        public string zdjecie { get; set; }
        public string film { get; set; }
        public Nullable<System.DateTime> data_utworzenia { get; set; }
        public int czas_wykonania { get; set; }
        public Nullable<int> trudnosc { get; set; }
        public string kategoria { get; set; }
        public string skladniki { get; set; }
    }
}
