
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Web.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Uzytkownik
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Uzytkownik()
    {

        this.PasswordReminder = new HashSet<PasswordReminder>();

    }


    public int Id { get; set; }

    public string nazwa { get; set; }

    public string login { get; set; }

    public string haslo { get; set; }

    public string email { get; set; }

    public string token { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PasswordReminder> PasswordReminder { get; set; }

}

}
